<?php $tipps = array (
	 array( "Das Leben ist wie ein Echo: Was wir aussenden, erhalten wir zurück.", "Unbekannt", "41" ),
array( "Der Verstand irrt, das Gefühl nie", "Robert Schumann", "30" ),
array( "Was wir erleben, ist ein Spiegelbild unserer Gedanken.", "Unbekannt", "25" ),
array( "Es ist kein Geheimnis. Du bekommst was du gibst", "Tupac Shakur", "26" ),
array( "Das alte Gesetz von Auge um Auge hinterlässt auf beiden Seiten Blinde.", "Martin Luther King", "9" ),
array( "Jeder kann jederzeit etwas aus dem machen, was aus ihm gemacht wurde.", "Unbekannt", "33" ),
array( "Krisen sind gute Zeiten, Denkanstöße zu Neuem zu erzwingen.", "Winfried Bauer", "34" ),
array( "Wie sind nur in dem Maße mit anderen zufrieden, wie wir mit uns zufrieden sind.", "Unbekannt", "35" ),
array( "Wer sich nicht selbst helfen kann, dem kann niemand helfen.", "Hans Pestalozzi", "2" ),
array( "Durch unsere Gedanken können wir ein Paradies zur Hölle machen und die Hölle zum Paradies.", "Unbekannt", "27" ),
array( "Solange wir jung sind arbeiten wir wie Sklaven, um uns etwas zu schaffen, wovon wir bequem leben können, wenn wir alt geworden sind. Und wenn wir alt sind merken wir, dass es zu spät ist, so zu leben", "Alexander Pope", "39" ),
array( "Je weniger Regeln wir in Bezug auf das Leben und die Menschen haben, umso zufriedener sind wir.", "Unbekannt", "42" ),
array( "Viele Menschen haben Angst zu sagen, was sie möchten. Deshalb bekommen sie es auch nicht.", "Madonna", "31" ),
array( "Die Erfüllung der Träume beginnt im Kopf.", "Unbekannt", "4" ),
array( "Wir können es nie allen Recht machen, nur uns selbst.", "Unbekannt", "5" ),
array( "Es ist nicht hilfreich, wenn wir unseren Niederlagen ein Denkmal setzen.", "Hedwig Keller", "11" ),
array( "Von misstrauischen Menschen kann man kein Vertrauen lernen, da sie ihm keine Chance geben.", "Unbekannt", "12" ),
array( "Werbung ist die Kunst, auf den Kopf zu zielen und die Brieftasche zu treffen. Kommunikation ist die Kunst, auf das Herz zu zielen, um den Kopf zu treffen", "Vance Packard", "25" ),
array( "Es ist besser ein kleines Licht anzuzünden, als über die Dunkelheit zu schimpfen.", "Laotze", "35" ),
array( "Es geschieht das, was wir glauben, und nicht das, was wir nicht wollen.", "Unbekannt", "34" ),
array( "Wenn wir anderen gegenüber schlechte Gefühle hegen, wer fühlt sich dann schlecht?", "Unbekannt", "31" ),
array( "Wenn man nicht versucht etwas zu tun, was jenseits des bereits Gemeisterten liegt, dann wird man nicht wachsen.", "Ralph Waldo Emerson", "37" ),
array( "Es zählt nicht, wo wir starten, sondern wohin wir wollen.", "Unbekannt", "40" ),
array( "Die wesentliche Voraussetzung für Glück ist die Bereitschaft, der zu sein, der man ist.", "Erasmus von Rotterdam", "18" ),
array( "Ein Problem ist DIE Gelegenheit, dein Bestes zu geben", "Duke Ellington", "1" ),
array( "Versagen ist lediglich ein Ereignis. Es macht uns nicht zum Versager.", "Unbekannt", "41" ),
array( "Wem hast Du HEUTE eine Freude gemacht?", "Dirk Schmidt", "38" ),
array( "Wenn wir etwas Neues erleben und schaffen möchten, dürfen wir keine ausgetretenen Pfade gehen.", "Unbekannt", "33" ),
array( "Um sich besser zu fühlen, genügt oft ein Wechsel der Blickrichtung.", "Unbekannt", "36" ),
array( "Wenn wir keinen Ausweg sehen, heißt das nicht, dass es keinen Ausweg gibt.", "Unbekannt", "14" ),
array( "Die Hoffnung stirbt immer zuletzt.", "Russisches Sprichwort", "43" ),
array( "Wir sollten niemandem die Erlaubnis geben, unsere Träume zu zerstören.", "Unbekannt", "37" ),
array( "Das meiste von dem, was wir sagen und tun, ist unnötig und wenn man es wegließe, würde man mit mehr Muße und weniger Unruhe leben", "Marc Aurel", "32" ),
array( "Die Menschen muss man nehmen, wie sie sind, nicht wie sie sein sollten", "Franz Schubert", "3" ),
array( "Wenn du Regeln brichst wird man sich an dich erinnern", "Douglas MacArthur", "2" ),
array( "Der Mensch wird geboren um zu leben, und nicht, um sich auf das Leben vorzubereiten.,Boris Pasternak", "0000-00-00", "39" ),
array( "Es sind unsere Erwartungen an andere, die uns unglücklich machen, nicht die anderen.", "Unbekannt", "27" ),
array( "Das merkwürdige Paradox ist, dass ich mich verändern kann, wenn ich mich so akzeptiere, wie ich bin.", "Carl Rogers", "24" ),
array( "Das Leben eines Menschen ist das, was seine Gedanken daraus machen.", "Marc Aurel", "26" ),
array( "Wir müssen uns nicht damit abfinden, wie wir sind. Wir können uns ändern.", "Unbekannt", "23" ),
array( "Unsere größte Gabe ist die Fähigkeit, Entscheidungen treffen zu können.", "Unbekannt", "22" ),
array( "Chancen entstehen dadurch, dass wir die Dinge in Frage stellen die wir tun!", "Unbekannt", "28" ),
array( "Je mehr wir uns mit Problemen beschäftigen, umso größer werden sie.", "Unbekannt", "19" ),
array( "Willst du einen guten Tag? Glaube an einen guten Tag.", "Norman Vincent Peale", "21" ),
array( "Manchmal müssen wir etwas verlieren, um seinen Wert zu entdecken.", "Unbekannt", "27" ),
array( "Ich habe oft Angst gehabt. Aber ich habe nicht klein beigegeben. Ich tat einfach so, als hätte ich keine Angst, und bald verschwand die Angst.", "Theodore Roosevelt", "3" ),
array( "Wer überzeugt ist, ein Pechvogel zu sein, wird vom Pech verfolgt.", "Unbekannt", "5" ),
array( "Wir sehen nur, was wir erwarten und wofür wir offen sind.", "Unbekannt", "7" ),
array( "In jeder Minute, die man mit Ärger verbringt, versäumt man sechzig glückliche Sekunden", "William Sommerset Maugham", "18" ),
array( "Keiner kann uns auf Dauer aufhalten – außer wir uns selbst.", "Unbekannt", "3" ),
array( "Innere Zufriedenheit müssen wir uns immer wieder neu erschaffen.", "Unbekannt", "9" ),
array( "Wenn man das Beste anstrebt und dafür sein Bestes gibt, hat man Erfolg.", "Unbekannt", "42" ),
array( "Vergleichen ist das Ende des Glücks und den Anfang der Unzufriedenheit.", "Unbekannt", "18" ),
array( "Probleme geben uns die Chance, Bekanntschaft mit unseren Fähigkeiten zu machen.", "Dirk Schmidt", "23" ),
array( "Auf Dauer nimmt die Seele die Farbe Deiner Gedanken an.", "Marc Aurel", "27" ),
array( "Der Wert einer Idee liegt in ihrer Umsetzung", "Thomas Alva Edison", "31" ),
array( "Wenn wir uns oft genug etwas einreden, dann glauben wir es – auch wenn es nicht wahr ist.", "Napoleon Hill", "35" ),
array( "Wir erleben, was wir erwarten oder befürchten.", "Unbekannt", "40" ),
array( "Wer nicht an Wunder glaubt, ist kein Realist.", "Johannes Mario Simmel", "41" ),
array( "Gott, gib mir die Kraft, die Dinge zu ändern die ich ändern kann. Die Gelassenheit, die Dinge hinzunehmen, die ich nicht ändern kann, und die Weisheit zwischen den beiden zu unterscheiden.", "Theologe Friedrich Christoph Oetinger (1702-1782)", "45" ),
array( "Wer sich erfüllt fühlen will, muss seinem Leben ganz bewusst einen Sinn geben.", "Unbekannt", "52" ),
array( "Wenn wir unser Glück nicht in uns selbst finden, dann finden wir es nirgendwo.", "Unbekannt", "71" ),
array( "Alles, was keine Emotionen auslöst, ist für unser Gehirn wertlos", "Dr. Hans-Georg Häusel", "66" ),
array( "Um nach vorne zu kommen und dort zu bleiben, kommt es nicht darauf an, wie gut du bist, wenn du gut bist, sondern wie gut du bist, wenn du schlecht bist", "Martina Navrátilová", "48" ),
array( "Für was bist Du DANKBAR?", "Dirk Schmidt", "67" ),
array( "Niemand ist so uninteressant wie ein Mensch ohne Interesse", "Thomas Browne", "65" ),
array( "Ein Problem ist halb gelöst, wenn es klar formuliert ist", "John Dewey", "63" ),
array( "Gib mir 6 Stunden einen Baum zu fällen und ich werde die ersten 4 mit dem Schärfen der Axt verbringen", "Abraham Lincoln", "58" ),
array( "Es kann dich niemand kränken, wenn du es nicht willst.", "Epiktet", "57" ),
array( "Das Unmögliche ist oft das, was noch niemand versucht hat.", "Anonym", "55" ),
array( "Vergeuden Sie nicht Ihre Zeit damit, das Leben eines anderen zu leben", "Steve Jobs", "54" ),
array( "Erledige zuerst die Aufgabe. Kümmere dich um die Genehmigung später", "Sargent Shriver", "69" ),
array( "Die wenigsten Fehltritte begeht man mit den Füssen", "Harald Juhnke", "46" ),
array( "Keine Gabe wirkt mächtiger und hinreißender im Menschen als die Phantasie", "Adalbert Stifter", "49" ),
array( "Mach' nur einmal das, von dem andere sagen, dass du es nicht schaffst, und du wirst nie wieder auf deren Grenzen achten müssen", "James R. Cook", "44" ),
array( "Man führt nicht mehr genug Selbstgespräche heutzutage. Man hat wohl Angst, sich selbst die Meinung zu sagen", "Jean Giraudoux", "70" ),
array( "Wir können anderen nur geben, was wir selbst besitzen.", "Unbekannt", "33" ),
array( "Die Entscheidungen, die wir treffen, diktieren das Leben das wir führen.", "Unbekannt", "61" ),
array( "Heute ist Dein Tag!", "Peter- T.Schulz", "66" ),
array( "Wir sind verantwortlich für das was wir tun, aber auch für das was wir nicht tun.", "Voltaire", "60" ),
array( "Man muss nicht nach dem Glück Ausschau halten: man trifft es auf dem Weg", "Isabelle Eberhardt", "51" ),
array( "Selbstvertrauen entsteht nur durch Handeln, nicht durch Unterlassung.", "Unbekannt", "71" ),
array( "Betrachte das Leben als eine Chance, die es zu nutzen gilt.", "Unbekannt", "64" ),
array( "Die nützlichsten Erfahrungen, die man macht, sind die schlechten.", "Thornton Wilder", "62" ),
array( "Sieh dich nicht wie du bist, sondern wie du sein möchtest.", "Unbekannt", "55" ),
array( "Unzufriedenheit ist die Strafe dafür, dass wir nicht mit dem zufrieden sind was wir besitzen.", "Unbekannt", "57" ),
array( "Jeder Tag ist ein neuer Anfang.", "T.S. Eliot", "56" ),
array( "Die modernen Sklaven werden nicht mit der Peitsche, sondern mit Terminkalendern angetrieben", "Isabelle Eberhardt", "48" ),
array( "Es gibt keine hoffnungslosen Situationen.Es gibt nur Menschen, die darüber hoffnungslos geworden sind.", "Clare Booth Luce", "47" ),
array( "Ein positiv denkender Mensch weigert sich nicht, das negative zur Kenntnis zu nehmen. Er weigert sich lediglich, sich ihm zu unterwerfen.", "Norman Vincent Peale", "28" ),
array( "Der Mensch ist kein Produkt der Umstände.Die Umstände sind ein Produkt des Menschen.", "Benjamin Disraeli", "41" ),
array( "Wenn jemand stirbt, heißt das noch lange nicht, dass er gelebt hat.", "Unbekannt", "43" ),
array( "Wir wissen, wer wir sind, aber nicht wer wir sein könnten.", "William Shakespeare", "19" ),
array( "Die, die wollen, finden Wege. Die, die nicht wollen, finden Gründe.", "Dirk Schmidt", "72" ),
array( "Wer aufhört, besser werden zu wollen, hört auf, gut zu sein.", "Marie von Ebner-Eschenbach", "17" ),
array( "Konzentriere dich nicht darauf, woher du kommst, sondern darauf, wohin du willst.", "Unbekannt", "24" ),
array( "Unsere Entscheidungen und Überzeugungen sind wie das Drehbuch eines Films.Sie entscheiden darüber, was wir sehen, erleben und fühlen.", "Unbekannt", "45" ),
array( "Im Grunde gibt es für den Menschen nur ein Unglück: dass er Umstände und Ereignisse als Unglück ansieht.", "Seneca", "12" ),
array( "Das Leben besteht im wesentlichen aus Glauben und Geduld. Wer diese besitzt, kommt zu einem herrlichen Ziel", "Rudolf von Tavel", "11" ),
array( "Scheitern ist ein Umweg, keine Sackgasse", "Zig Ziglar", "14" ),
array( "Fange keinen Wettlauf mit anderen an, laufe gegen dich selbst! ", "Dirk Schmidt", "15" ),
array( "Glücklich ist, wer daran glaubt, dass es niemals zu spät ist, neu zu beginnen.", "Unbekannt", "18" ),
array( "Halte etwas für schwer und du tust dich schwer.", "Unbekannt", "22" ),
array( "Ein Optimist mag ein Licht sehen, wo keines ist. Aber warum muss es der Pessimist immer wieder ausblasen?", "Michel de Saint Pierre.", "25" ),
array( "Lob ist wie eine Feder. Von Zeit zu Zeit ein Lob, und Menschen bekommen Flügel", "Phil Bosmans", "52" ),
array( "Wir sind, was wir aus unserem Leben machen.", "Unbekannt", "56" ),
array( "Die Zunge kann lügen - der Körper nie.", "Samy Molcho", "58" ),
array( "Ein Durchschnittsmensch, der sich auf den wirkungsvollsten Punkt konzentriert, wird erfolgreicher sein als ein Genie, das sich verzettelt.", "Wolfgang Mewes", "60" ),
array( "Der Mensch ist umso reicher, je mehr Dinge er lassen kann.", "Henry David Thoreau", "55" ),
array( "Sonnenschein ist köstlich, Regen erfrischt, Wind kräftigt, Schnee erheitert. Es gibt kein schlechtes Wetter, es gibt nur verschiedene Arten von Gutem.", "John Ruski", "49" ),
array( "Mit Absichten kann man nicht berühmt werden.", "Henry Ford", "44" ),
array( "Nur für etwas, das dich wirklich bewegt, kannst du wirklich etwas bewegen", "KarlHeinz Karius", "42" ),
array( "Die Augen sind die Fenster der Seele.", "Hildegard von Bingen", "30" ),
array( "Pessimisten sehen eine Schwierigkeit bei jeder Gelegenheit. Optimisten sehen eine Gelegenheit in jeder Schwierigkeit.", "Anonym", "46" ),
array( "Alles, was uns wirklich nützt, ist für wenig Geld zu haben, nur das Überflüssige kostet viel.", "Axel Munthe", "39" ),
array( "Du bist sofort die Hälfte deiner Probleme los, wenn du den Leuten nicht länger erlaubst, dass SIE dir sagen, was DU willst.", "Vernon Law", "35" ),
array( "Veränderungen machen uns vor allen Dingen deshalb Angst, weil sie uns dazu zwingen, uns aus der Hängematte der Gewohnheit heraus zu begeben", "Helga Schäferling", "23" ),
array( "Man kann nicht über seinen Schatten springen, aber man muss auch nicht immer in seinem Schatten leben", "Adolph Lowe", "5" ),
array( "Wer nichts erwartet, wird selten enttäuscht", "Ewald Balser", "7" ),
array( "Was wir am nötigsten brauchen, ist ein Mensch,der uns zwingt, das zu tun, was wir können", "Ralph Waldo Emerson", "3" ),
array( "Dort, wo die Vorstellungskraft fehlt, kann es keine Leidenschaft und als Konsequenz keine Liebe geben", "William Godwin", "1" ),
array( "Manchmal schweben Gelegenheiten direkt an deiner Nase vorbei. Arbeite hart, sei fleißig, halte dich bereit. Wenn du eine Chance bekommst dann ergreife sie", "Julie Andrews", "9" ),
array( "Jeder Mensch will glücklich werden", "das ist falsch. Jeder Mensch soll glücklich machen", "20" ),
array( "Falls Du glaubst, dass Du zu klein bist, um etwas zu bewirken, dann versuche mal zu schlafen, wenn ein Moskito im Zimmer ist", "Dalei Lama", "55" ),
array( "Die Gesundheit ist wie das Salz: Man bemerkt nur, wenn es fehlt.", "Aus China", "69" ),
array( "Wir alle werden vor eine Serie großartiger Möglichkeiten gestellt - brillant maskiert als unlösbare Probleme", "John William Gardner", "59" ),
array( "Es ist nie zu spät, der zu werden, der Sie hätten sein können.", "George Eliot", "56" ),
array( "Präzise zu planen kostet auch nicht mehr Energie als träumen, wünschen und hoffen.", "Henry Cohen", "58" ),
array( "Wenn es um dich geht, benutze deinen Kopf", "wenn es um andere geht, benutze dein Herz", "64" ),
array( "Das Glück bevorzugt den, der vorbereitet ist.", "Louis Pasteur", "18" ),
array( "Wer lächelt, statt zu toben, ist immer der Stärkere.", "Japanisches Sprichwort", "38" ),
array( "Was du heute denkst, wirst du morgen tun", "Leo Tolstoi", "33" ),
array( "Der Mensch, der Berge versetzte, war derselbe, der anfing, kleine Steine wegzutragen.", "Chinesisches Sprichwort", "70" ),
array( "Jemanden lieben heißt, ein für die anderen unsichtbares Wunder zu sehen.", "Mauriac", "56" ),
array( "Zufriedenheit hält einem sogar eine Erkältung vom Leib.", "Friedrich Nietzsche", "30" ),
array( "Es gibt im Leben nur zwei Sünden: Die eine ist, zu wünschen ohne zu handeln", "die andere ist, zu handeln ohne Ziel.", "5" ),
array( "Viele Probleme erledigen sich von selbst, wenn man sie nicht dabei stört", "William Sloane Coffin", "12" ),
array( "Die Schwierigkeiten wachsen, je näher man ans Ziel kommt", "Alfred Nobel", "51" ),
array( "Entweder werden wir einen Weg finden oder wie machen einen", "Hannibal", "50" ),
array( "Jeder Zustand ist so gut, als man ihn sich macht", "Paul de Lagarde", "61" ),
array( "Wir beschäftigen uns mit großem Eifer mit uns selbst und bilden uns hinterher ein, die Menschen zu kennen", "Iwan Sergejewitsch Turgenjew", "57" ),
array( "Welchen Menschen hast Du HEUTE eine Freude gemacht?", "Dirk Schmidt", "7" ),
array( "Denken Sie weniger und leben Sie mehr", "Johann Georg Hamann", "8" ),
array( "Jeder Zustand ist so gut, als man ihn sich macht", "Paul de Lagarde", "68" ),
array( "Motivation ist wie Waschen - deshalb empfehlen wir sie täglich", "Zig Ziglar", "66" ),
array( "Vorsicht ist die Einstellung, die das Leben sicherer macht, aber selten glücklicher", "Samuel Johnson", "55" ),
array( "Was ich will, kann ich auch", "Grigori Jefimowitsch Rasputin", "71" ),
array( "Nur wenn wir glauben, besiegt zu sein, sind wir es.", "Anonym", "45" ),
array( "Wenn Du zu wenig Erfolg hast, erhöhe die Geschwindigkeit, mit der du Fehler machst.", "Thomas Edison", "4" ),
array( "Was wir in der Industrie im Umgang mit Menschen gelernt haben ist, dass die Menschen nicht nur für Geld arbeiten, und das Geld in Sachen Motivation nicht das effektivste Werkzeug ist", "Akio Morita", "62" ),
array( "Erfolg ersetzt alle Argumente", "Sigmund Graff", "63" ),
array( "Es hat keinen Sinn, Sorgen im Alkohol ertränken zu wollen, denn Sorgen sind gute Schwimmer.", "Robert Musil", "60" ),
array( "Dem Menschen einen Glauben schenken, heißt seine Kraft verzehnfachen ", "Gustave Le Bon", "67" ),
array( "Man muss die Menschen so belehren, als ob man sie nicht belehrte, und unbekannte Dinge vortragen, als seien sie nur vergessen", "Alexander Pope", "52" ),
array( "Man überschätzt leicht das eigene Wirken und Tun in seiner Wichtigkeit gegenüber dem, was man durch andere geworden ist", "Dietrich Bonhoeffer", "33" ),
array( "Es gibt eine Möglichkeit, es besser zu machen - finde sie", "Thomas Alva Edison", "55" ),
array( "Die meisten verwechseln Dabeisein mit Erleben", "Max Frisch", "58" ),
array( "Wer weiß, welche Rolle er im Leben anderer spielt, braucht ihnen nichts mehr vorzuspielen.", "Ernst Ferstl", "56" ),
array( "Gegen Angriffe kann man sich wehren, gegen Lob ist man machtlos.", "Sigmund Freud", "61" ),
array( "Durch Bewegung überwindet man Kälte. Durch Stillhalten überwindet man Hitze. Der Weise vermag es, durch Reinheit und Ruhe alle Dinge der Welt ins Gleichmaß zu bringen.", "Laotse", "66" ),
array( "Aus Niederlagen lernt man leichter als aus Siegen", "Gustav Stresemann", "64" ),
array( "Glück hilft nur manchmal, Arbeit immer", "Friedrich Rückert", "32" ),
array( "Die Erfahrungen sind wie die Samenkörner, aus denen die Klugheit emporwächst", "Konrad Adenauer", "23" ),
array( "Ein Mensch mit Überzeugung ist stärker als 99 andere, die bloß Interessen verfolgen", "John Stuart Mill", "27" ),
array( "Der Kluge lernt nach dem ersten Fehler, der Dumme nach dem x-ten Fehler, der Weise lernt nie aus", "Chinesisches Sprichwort", "5" ),
array( "Es gibt nichts, was die Menschen lieber erhalten möchten und weniger pflegen als ihre Gesundheit.", "Jean de la Bruyère", "12" ),
array( "Dem Geld darf man nicht nachlaufen, man muss ihm entgegenkommen", "Aristoteles Onassis", "41" ),
array( "Bei uns sind alle clever, nur hört keiner dem anderen zu.", "Norbert Blüm", "70" ),
array( "Ein guter Arbeitstag beginnt mit Zielen", "Götz Werner", "48" ),
array( "Der Vorteil der Klugheit besteht darin, dass man sich dumm stellen kann. Das Gegenteil ist schon schwieriger", "Kurt Tucholsky", "54" ),
array( "Glück ist, seine Freude in der Freude des anderen zu finden.", "Georges Bernanos", "38" ),
array( "Gelassenheit kann man lernen. Man braucht dazu nur Offenheit, Motivation, ein bisschen Ausdauer und vor allem Bereitschaft, sich von den alten, eingefahrenden Bahnen zu lösen, in denen unser Denken und Handeln sich häufig bewegt", "Ludwig Bechstein", "25" ),
array( "Die Wissenschaftler bemühen sich, das Unmögliche möglich zu machen. Die Politiker bemühen sich oft, das Mögliche unmöglich zu machen", "Bertrand Arthur William Russell", "26" ),
array( "Die Menschen sehen nur das, was sie erwarten zu sehen", "Ralph Waldo Emerson", "19" ),
array( "Es ist besser die richtige Arbeit zu tun (= Effektivität), als eine Arbeit nur richtig zu tun (= Effizienz)", "Peter F. Drucker", "68" ),
array( "Im Leben fängt man dann und wann wieder mal von vorne an", "Wilhelm Busch", "14" ),
array( "Erfolg steigt nur zu Kopf, wenn dafür genügend Hohlraum vorhanden ist", "Karl Kraus", "10" ),
array( "Nutze die Talente, die Du hast. Die Wälder wären sehr still, wenn nur die begabtesten Vögel sängen", "Henry van Dyke", "18" ),
array( "Wer lachen kann, dort, wo er hätte heulen können, bekommt wieder Lust zum Leben", "Werner Finck", "7" ),
array( "Mancher glaubt, beliebt zu sein, aber man hat sich nur an seine Art gewöhnt", "Upton Sinclair", "11" ),
array( "Das Recht zu hoffen ist die mächtigste menschliche Motivation die ich kenne", "Aga Khan IV", "3" ),
array( "Kein Mensch ist geschäftlich erfolgreich, wenn er seine Arbeit nicht liebt", "Florence Scovel Shinn", "46" ),
array( "Erfahrungen sind Maßarbeit. Sie passen nur dem, der sie macht", "Carlo Levi", "39" ),
array( "Es gehört mehr Mut dazu, seine Meinung zu ändern, als ihr treu zu bleiben.", "Friedrich Hebbel", "45" ),
array( "Ändere Deine Einstellung zu den Menschen, und die Menschen ändern ihre Einstellung zu Dir.", "Samy Molcho", "49" ),
array( "Es ist die Aufgabe des Managements, den Mitarbeitern Visionen zu geben", "das ist die allerbeste Motivation", "52" ),
array( "Der ideale Tag wird nie kommen. Er ist heute, wenn wir ihn dazu machen", "Horaz", "71" ),
array( "Fang an. Dadurch allein kann das Unmögliche möglich werden", "Thomas Carlyle", "65" ),
array( "Der wirkliche Reichtum eines Menschen ist der Reichtum seiner wirklichen Beziehungen.", "Karl Marx", "50" ),
array( "Ich zahle nicht gute Löhne, weil ich viel Geld habe, sondern ich habe viel Geld weil ich gute Löhne zahle", "Robert Bosch", "29" ),
array( "Das Leben besteht im Wesentlichen aus Glauben und Geduld. Wer diese besitzt, kommt zu einem herrlichen Ziel", "Rudolf von Tavel", "27" ),
array( "Alles geht vorüber sagt mancher - aber er hat dabei nicht an die Dummheit gedacht", "Siegfried Lowitz", "32" ),
array( "Wenn Gott mich anders gewollt hätte, hätte er mich anders gemacht.", "Johann Wolfgang von Goethe", "22" ),
array( "Wenn wir nicht an uns selbst glauben, können wir nicht erwarten, dass es andere tun.", "Chinesisches Sprichwort", "33" ),
array( "Der Unterschied zwischen Erfolg und Misserfolg ist der Unterschied zwischen Richtigtun und Fast-Richtigtun.", "Edward Simmons", "40" ),
array( "Alles was du in deinem Leben erreichst oder nicht erreichst, ist das direkte Resultat, deiner Gedanken", "James Allen", "41" ),
array( "Man hilft den Menschen nicht, wenn man für sie tut, was Sie selbst tun könnten", "Abraham Lincoln", "45" ),
array( "Das Schwierigste am Leben ist es, Herz und Kopf dazu zu bringen, zusammenzuarbeiten. In meinem Fall verkehren sie noch nicht mal auf freundschaftlicher Basis", "Woody Allen", "49" ),
array( "Gewinne mit Gleichmut, verliere mit einem Lächeln", "Ludwig Wallner", "54" ),
array( "Zukunft – das ist die Zeit, in der Du bereust, dass Du das, was Du heute tun kannst, nicht getan hast.", "Amerikanisches Sprichwort", "51" ),
array( "Man kann nicht heute Apfelbäume pflanzen und schon im nächsten Jahr die Früchte ernten", "Berthold Beitz", "58" ),
array( "Ein Mensch, der Berge versetzt, beginnt damit, indem er kleine Steine abträgt", "William Faulkner", "71" ),
array( "Die wichtigste Stunde ist immer die Gegenwart, der bedeutendste Mensch ist immer der, der Dir gerade gegenübersteht, und das notwendigste Wohl ist immer die Liebe.", "Meister Eckhart", "70" ),
array( "Deine Zukunft ist, wozu du sie machen willst. Zukunft heißt wollen", "Patrick White", "64" ),
array( "Die Neugier steht immer an erster Stelle eines Problems, das gelöst werden will", "Galileo Galilei", "61" ),
array( "Zeit hat man nur, wenn man sie sich nimmt", "Karl Heinrich Waggerl", "57" ),
array( "Viele Menschen sehen die Dinge, wie sie sind und sagen - warum? Ich aber träume von Dingen, die nie gewesen sind und sage - warum nicht?", "Robert F. Kennedy", "55" ),
array( "Was immer du tun kannst oder wovon du träumst, fange damit an! Mut hat Genie, Kraft und Zauber.", "Johann Wolfgang von Goethe", "52" ),
array( "Was hat es für einen Sinn schnell zu laufen, wenn Du auf dem falschen Weg bist?", "Chinesisches Sprichwort", "48" ),
array( "Eigenliebe ist der Beginn einer lebenslangen Romanze", "Oscar Wilde", "24" ),
array( "Lass niemals einen Tag vergehen, ohne dass du zu dir sagst: Morgen mache ich es besser", "Brigham Young", "26" ),
array( "Faulheit ist die Angewohnheit, sich auszuruhen, bevor man müde ist", "Jules Renard", "16" ),
array( "Wenn der Wind des Wandels weht, bauen die einen Schutzmauern, die anderen Windmühlen.", "Chinesisches Sprichwort", "34" ),
array( "Wenn andere glauben, man ist am Ende, so muss man erst richtig anfangen.", "Konrad Adenauer", "15" ),
array( "Erfolg ist nicht auf Erfolg aufgebaut. Er ist auf Fehlern aufgebaut. Er ist auf Frustration aufgebaut. Manchmal ist er auf Katastrophen aufgebaut", "Sumner Redstone", "19" ),
array( "Vermögen um den Preis der Gesundheit zu erwerben, heißt, sich die Füße abzuschneiden, um dafür ein Paar Stiefel zu kaufen.", "Prentice Mulford", "35" ),
array( "Wenn man seinem Passbild ähnlich zu sehen beginnt, sollte man schleunigst Urlaub machen", "Vico Torriani", "45" ),
array( "Je näher man an seinen Traum herankommt, um so mehr wird der persönliche Lebensweg zum eigentlichen Lebensziel.", "Paulo Coelho", "48" ),
array( "Manchmal träum' ich davon, dass ich nicht immer nur blühen muss, sondern Zeit und Ruhe habe, um Kraft für neue Triebe zu sammeln.", "A. Schwarz", "52" ),
array( "Es ist besser, unvollkommene Entscheidungen durchzuführen, als beständig nach vollkommenen Entscheidungen zu suchen, die es niemals geben wird", "Charles de Gaulle", "54" ),
array( "Wahrer Reichtum besteht nicht im Besitz, sondern im Genießen.", "Ralph Waldo Emerson", "44" ),
array( "Wir unterschätzen das, was wir haben und überschätzen das, was wir sind.", "Marie von Ebner-Eschenbach", "40" ),
array( "Bete nicht um eine leichtere Last, sondern um einen stärkeren Rücken.", "Teresa von Avila", "41" ),
array( "Zeit hat man nur, wenn man sie sich nimmt", "Karl Heinrich Waggerl", "47" ),
array( "Zufall ist ein Wort ohne Sinn – nichts kann ohne Ursache existieren", "Voltaire", "55" ),
array( "Es gibt nur wenig Erfolg, wo wenig gelacht wird", "Andrew Carnegie", "7" ),
array( "Es ist von größter Wichtigkeit, zu lernen über sich selbst zu lachen", "Katherine Mansfield", "38" ),
array( "Gib niemals auf - höchstens einen Brief.", "Heinz Erhardt", "71" ),
array( "Wer Gutes in anderen sieht, entdeckt das Beste in sich selbst.", "Martin Walsh", "65" ),
array( "Nicht was wir erleben, sondern wie wir empfinden, was wir erleben, macht unser Schicksal aus.", "Marie von Ebner-Eschenbach", "62" ),
array( "Rechne mit dem Schlimmsten, dann kannst Du nur angenehm überrascht werden.", "Japanisches Sprichwort", "63" ),
array( "Die, die wollen, finden Wege. Die, die nicht wollen, finden Gründe.", "Dirk Schmidt", "72" ),
array( "Die guten Seiten des Lebens zu erkennen nimmt nicht mehr Zeit in Anspruch, als die schlechten zu sehen", "Jimmy Buffett", "61" ),
array( "Erfolg besteht zu 20% aus Talent und Training und zu 80% aus Wille", "Dirk Nowitzki", "58" ),
array( "Unser Schicksal hängt nicht von den Sternen ab, sondern von unserem Handeln. ", "William Shakespeare", "68" ),
array( "Es ist viel einfacher sich hinterher zu entschuldigen, als vorher um Erlaubnis zu bitten", "Grace Hopper", "60" ),
array( "Geld kann etwas anfachen, aber es kann nicht alleine und auch nicht für sehr lange brennen", "Igor Fjodorowitsch Strawinsky", "49" ),
array( "Bedenke: Nicht zu bekommen was man will, ist manchmal ein großer Glücksfall", "Dalei Lama", "40" ),
array( "Wer keine Probleme löst, darf sich nicht wundern, dass sich keiner für das Angebot interessiert", "Peter Sawtschenko", "27" ),
array( "Je mehr Vergnügen du an deiner Arbeit hast, desto besser wird sie bezahlt", "Mark Twain", "29" ),
array( "Das Wesentliche ist zu wissen was du willst", "Robert Collier", "24" ),
array( "Ich bin nie mit der Mode gegangen. Ich habe sie gemacht", "Pierre Cardin", "26" ),
array( "Das Leben ist wie ein Echo: Was wir aussenden, erhalten wir zurück.", "Unbekannt", "41" ),
array( "Der Verstand irrt, das Gefühl nie", "Robert Schumann", "30" ),
array( "Was wir erleben, ist ein Spiegelbild unserer Gedanken.", "Unbekannt", "25" ),
array( "Es ist kein Geheimnis. Du bekommst was du gibst", "Tupac Shakur", "26" ),
array( "Das alte Gesetz von Auge um Auge hinterlässt auf beiden Seiten Blinde.", "Martin Luther King", "9" ),
array( "Jeder kann jederzeit etwas aus dem machen, was aus ihm gemacht wurde.", "Unbekannt", "33" ),
array( "Krisen sind gute Zeiten, Denkanstöße zu Neuem zu erzwingen.", "Winfried Bauer", "34" ),
array( "Wie sind nur in dem Maße mit anderen zufrieden, wie wir mit uns zufrieden sind.", "Unbekannt", "35" ),
array( "Wer sich nicht selbst helfen kann, dem kann niemand helfen.", "Hans Pestalozzi", "2" ),
array( "Durch unsere Gedanken können wir ein Paradies zur Hölle machen und die Hölle zum Paradies.", "Unbekannt", "27" ),
array( "Solange wir jung sind arbeiten wir wie Sklaven, um uns etwas zu schaffen, wovon wir bequem leben können, wenn wir alt geworden sind. Und wenn wir alt sind merken wir, dass es zu spät ist, so zu leben", "Alexander Pope", "39" ),
array( "Je weniger Regeln wir in Bezug auf das Leben und die Menschen haben, umso zufriedener sind wir.", "Unbekannt", "42" ),
array( "Viele Menschen haben Angst zu sagen, was sie möchten. Deshalb bekommen sie es auch nicht.", "Madonna", "31" ),
array( "Die Erfüllung der Träume beginnt im Kopf.", "Unbekannt", "4" ),
array( "Wir können es nie allen Recht machen, nur uns selbst.", "Unbekannt", "5" ),
array( "Es ist nicht hilfreich, wenn wir unseren Niederlagen ein Denkmal setzen.", "Hedwig Keller", "11" ),
array( "Von misstrauischen Menschen kann man kein Vertrauen lernen, da sie ihm keine Chance geben.", "Unbekannt", "12" ),
array( "Werbung ist die Kunst, auf den Kopf zu zielen und die Brieftasche zu treffen. Kommunikation ist die Kunst, auf das Herz zu zielen, um den Kopf zu treffen", "Vance Packard", "25" ),
array( "Es ist besser ein kleines Licht anzuzünden, als über die Dunkelheit zu schimpfen.", "Laotze", "35" ),
array( "Es geschieht das, was wir glauben, und nicht das, was wir nicht wollen.", "Unbekannt", "34" ),
array( "Wenn wir anderen gegenüber schlechte Gefühle hegen, wer fühlt sich dann schlecht?", "Unbekannt", "31" ),
array( "Wenn man nicht versucht etwas zu tun, was jenseits des bereits Gemeisterten liegt, dann wird man nicht wachsen.", "Ralph Waldo Emerson", "37" ),
array( "Es zählt nicht, wo wir starten, sondern wohin wir wollen.", "Unbekannt", "40" ),
array( "Die wesentliche Voraussetzung für Glück ist die Bereitschaft, der zu sein, der man ist.", "Erasmus von Rotterdam", "18" ),
array( "Ein Problem ist DIE Gelegenheit, dein Bestes zu geben", "Duke Ellington", "1" ),
array( "Versagen ist lediglich ein Ereignis. Es macht uns nicht zum Versager.", "Unbekannt", "41" ),
array( "Wem hast Du HEUTE eine Freude gemacht?", "Dirk Schmidt", "38" ),
array( "Wenn wir etwas Neues erleben und schaffen möchten, dürfen wir keine ausgetretenen Pfade gehen.", "Unbekannt", "33" ),
array( "Um sich besser zu fühlen, genügt oft ein Wechsel der Blickrichtung.", "Unbekannt", "36" ),
array( "Wenn wir keinen Ausweg sehen, heißt das nicht, dass es keinen Ausweg gibt.", "Unbekannt", "14" ),
array( "Die Hoffnung stirbt immer zuletzt.", "Russisches Sprichwort", "43" ),
array( "Wir sollten niemandem die Erlaubnis geben, unsere Träume zu zerstören.", "Unbekannt", "37" ),
array( "Das meiste von dem, was wir sagen und tun, ist unnötig und wenn man es wegließe, würde man mit mehr Muße und weniger Unruhe leben", "Marc Aurel", "32" ),
array( "Die Menschen muss man nehmen, wie sie sind, nicht wie sie sein sollten", "Franz Schubert", "3" ),
array( "Wenn du Regeln brichst wird man sich an dich erinnern", "Douglas MacArthur", "2" ),
array( "Der Mensch wird geboren um zu leben, und nicht, um sich auf das Leben vorzubereiten.,Boris Pasternak", "0000-00-00", "39" ),
array( "Es sind unsere Erwartungen an andere, die uns unglücklich machen, nicht die anderen.", "Unbekannt", "27" ),
array( "Das merkwürdige Paradox ist, dass ich mich verändern kann, wenn ich mich so akzeptiere, wie ich bin.", "Carl Rogers", "24" ),
array( "Das Leben eines Menschen ist das, was seine Gedanken daraus machen.", "Marc Aurel", "26" ),
array( "Wir müssen uns nicht damit abfinden, wie wir sind. Wir können uns ändern.", "Unbekannt", "23" ),
array( "Unsere größte Gabe ist die Fähigkeit, Entscheidungen treffen zu können.", "Unbekannt", "22" ),
array( "Chancen entstehen dadurch, dass wir die Dinge in Frage stellen die wir tun!", "Unbekannt", "28" ),
array( "Je mehr wir uns mit Problemen beschäftigen, umso größer werden sie.", "Unbekannt", "19" ),
array( "Willst du einen guten Tag? Glaube an einen guten Tag.", "Norman Vincent Peale", "21" ),
array( "Manchmal müssen wir etwas verlieren, um seinen Wert zu entdecken.", "Unbekannt", "27" ),
array( "Ich habe oft Angst gehabt. Aber ich habe nicht klein beigegeben. Ich tat einfach so, als hätte ich keine Angst, und bald verschwand die Angst.", "Theodore Roosevelt", "3" ),
array( "Wer überzeugt ist, ein Pechvogel zu sein, wird vom Pech verfolgt.", "Unbekannt", "5" ),
array( "Wir sehen nur, was wir erwarten und wofür wir offen sind.", "Unbekannt", "7" ),
array( "In jeder Minute, die man mit Ärger verbringt, versäumt man sechzig glückliche Sekunden", "William Sommerset Maugham", "18" ),
array( "Keiner kann uns auf Dauer aufhalten – außer wir uns selbst.", "Unbekannt", "3" ),
array( "Innere Zufriedenheit müssen wir uns immer wieder neu erschaffen.", "Unbekannt", "9" ),
array( "Wenn man das Beste anstrebt und dafür sein Bestes gibt, hat man Erfolg.", "Unbekannt", "42" ),
array( "Vergleichen ist das Ende des Glücks und den Anfang der Unzufriedenheit.", "Unbekannt", "18" ),
array( "Probleme geben uns die Chance, Bekanntschaft mit unseren Fähigkeiten zu machen.", "Dirk Schmidt", "23" ),
array( "Auf Dauer nimmt die Seele die Farbe Deiner Gedanken an.", "Marc Aurel", "27" ),
array( "Der Wert einer Idee liegt in ihrer Umsetzung", "Thomas Alva Edison", "31" ),
array( "Wenn wir uns oft genug etwas einreden, dann glauben wir es – auch wenn es nicht wahr ist.", "Napoleon Hill", "35" ),
array( "Wir erleben, was wir erwarten oder befürchten.", "Unbekannt", "40" ),
array( "Wer nicht an Wunder glaubt, ist kein Realist.", "Johannes Mario Simmel", "41" ),
array( "Gott, gib mir die Kraft, die Dinge zu ändern die ich ändern kann. Die Gelassenheit, die Dinge hinzunehmen, die ich nicht ändern kann, und die Weisheit zwischen den beiden zu unterscheiden.", "Theologe Friedrich Christoph Oetinger (1702-1782)", "45" ),
array( "Wer sich erfüllt fühlen will, muss seinem Leben ganz bewusst einen Sinn geben.", "Unbekannt", "52" ),
array( "Wenn wir unser Glück nicht in uns selbst finden, dann finden wir es nirgendwo.", "Unbekannt", "71" ),
array( "Alles, was keine Emotionen auslöst, ist für unser Gehirn wertlos", "Dr. Hans-Georg Häusel", "66" ),
array( "Um nach vorne zu kommen und dort zu bleiben, kommt es nicht darauf an, wie gut du bist, wenn du gut bist, sondern wie gut du bist, wenn du schlecht bist", "Martina Navrátilová", "48" ),
array( "Für was bist Du DANKBAR?", "Dirk Schmidt", "67" ),
array( "Niemand ist so uninteressant wie ein Mensch ohne Interesse", "Thomas Browne", "65" ),
array( "Ein Problem ist halb gelöst, wenn es klar formuliert ist", "John Dewey", "63" ),
array( "Gib mir 6 Stunden einen Baum zu fällen und ich werde die ersten 4 mit dem Schärfen der Axt verbringen", "Abraham Lincoln", "58" ),
array( "Es kann dich niemand kränken, wenn du es nicht willst.", "Epiktet", "57" ),
array( "Das Unmögliche ist oft das, was noch niemand versucht hat.", "Anonym", "55" ),
array( "Vergeuden Sie nicht Ihre Zeit damit, das Leben eines anderen zu leben", "Steve Jobs", "54" ),
array( "Erledige zuerst die Aufgabe. Kümmere dich um die Genehmigung später", "Sargent Shriver", "69" ),
array( "Die wenigsten Fehltritte begeht man mit den Füssen", "Harald Juhnke", "46" ),
array( "Keine Gabe wirkt mächtiger und hinreißender im Menschen als die Phantasie", "Adalbert Stifter", "49" ),
array( "Mach' nur einmal das, von dem andere sagen, dass du es nicht schaffst, und du wirst nie wieder auf deren Grenzen achten müssen", "James R. Cook", "44" ),
array( "Man führt nicht mehr genug Selbstgespräche heutzutage. Man hat wohl Angst, sich selbst die Meinung zu sagen", "Jean Giraudoux", "70" ),
array( "Wir können anderen nur geben, was wir selbst besitzen.", "Unbekannt", "33" ),
array( "Die Entscheidungen, die wir treffen, diktieren das Leben das wir führen.", "Unbekannt", "61" ),
array( "Heute ist Dein Tag!", "Peter- T.Schulz", "66" ),
array( "Wir sind verantwortlich für das was wir tun, aber auch für das was wir nicht tun.", "Voltaire", "60" ),
array( "Man muss nicht nach dem Glück Ausschau halten: man trifft es auf dem Weg", "Isabelle Eberhardt", "51" ),
array( "Selbstvertrauen entsteht nur durch Handeln, nicht durch Unterlassung.", "Unbekannt", "71" ),
array( "Betrachte das Leben als eine Chance, die es zu nutzen gilt.", "Unbekannt", "64" ),
array( "Die nützlichsten Erfahrungen, die man macht, sind die schlechten.", "Thornton Wilder", "62" ),
array( "Sieh dich nicht wie du bist, sondern wie du sein möchtest.", "Unbekannt", "55" ),
array( "Unzufriedenheit ist die Strafe dafür, dass wir nicht mit dem zufrieden sind was wir besitzen.", "Unbekannt", "57" ),
array( "Jeder Tag ist ein neuer Anfang.", "T.S. Eliot", "56" ),
array( "Die modernen Sklaven werden nicht mit der Peitsche, sondern mit Terminkalendern angetrieben", "Isabelle Eberhardt", "48" ),
array( "Es gibt keine hoffnungslosen Situationen.Es gibt nur Menschen, die darüber hoffnungslos geworden sind.", "Clare Booth Luce", "47" ),
array( "Ein positiv denkender Mensch weigert sich nicht, das negative zur Kenntnis zu nehmen. Er weigert sich lediglich, sich ihm zu unterwerfen.", "Norman Vincent Peale", "28" ),
array( "Der Mensch ist kein Produkt der Umstände.Die Umstände sind ein Produkt des Menschen.", "Benjamin Disraeli", "41" ),
array( "Wenn jemand stirbt, heißt das noch lange nicht, dass er gelebt hat.", "Unbekannt", "43" ),
array( "Wir wissen, wer wir sind, aber nicht wer wir sein könnten.", "William Shakespeare", "19" ),
array( "Die, die wollen, finden Wege. Die, die nicht wollen, finden Gründe.", "Dirk Schmidt", "72" ),
array( "Wer aufhört, besser werden zu wollen, hört auf, gut zu sein.", "Marie von Ebner-Eschenbach", "17" ),
array( "Konzentriere dich nicht darauf, woher du kommst, sondern darauf, wohin du willst.", "Unbekannt", "24" ),
array( "Unsere Entscheidungen und Überzeugungen sind wie das Drehbuch eines Films.Sie entscheiden darüber, was wir sehen, erleben und fühlen.", "Unbekannt", "45" ),
array( "Im Grunde gibt es für den Menschen nur ein Unglück: dass er Umstände und Ereignisse als Unglück ansieht.", "Seneca", "12" ),
array( "Das Leben besteht im wesentlichen aus Glauben und Geduld. Wer diese besitzt, kommt zu einem herrlichen Ziel", "Rudolf von Tavel", "11" ),
array( "Scheitern ist ein Umweg, keine Sackgasse", "Zig Ziglar", "14" ),
array( "Fange keinen Wettlauf mit anderen an, laufe gegen dich selbst! ", "Dirk Schmidt", "15" ),
array( "Glücklich ist, wer daran glaubt, dass es niemals zu spät ist, neu zu beginnen.", "Unbekannt", "18" ),
array( "Halte etwas für schwer und du tust dich schwer.", "Unbekannt", "22" ),
array( "Ein Optimist mag ein Licht sehen, wo keines ist. Aber warum muss es der Pessimist immer wieder ausblasen?", "Michel de Saint Pierre.", "25" ),
array( "Lob ist wie eine Feder. Von Zeit zu Zeit ein Lob, und Menschen bekommen Flügel", "Phil Bosmans", "52" ),
array( "Wir sind, was wir aus unserem Leben machen.", "Unbekannt", "56" ),
array( "Die Zunge kann lügen - der Körper nie.", "Samy Molcho", "58" ),
array( "Ein Durchschnittsmensch, der sich auf den wirkungsvollsten Punkt konzentriert, wird erfolgreicher sein als ein Genie, das sich verzettelt.", "Wolfgang Mewes", "60" ),
array( "Der Mensch ist umso reicher, je mehr Dinge er lassen kann.", "Henry David Thoreau", "55" ),
array( "Sonnenschein ist köstlich, Regen erfrischt, Wind kräftigt, Schnee erheitert. Es gibt kein schlechtes Wetter, es gibt nur verschiedene Arten von Gutem.", "John Ruski", "49" ),
array( "Mit Absichten kann man nicht berühmt werden.", "Henry Ford", "44" ),
array( "Nur für etwas, das dich wirklich bewegt, kannst du wirklich etwas bewegen", "KarlHeinz Karius", "42" ),
array( "Die Augen sind die Fenster der Seele.", "Hildegard von Bingen", "30" ),
array( "Pessimisten sehen eine Schwierigkeit bei jeder Gelegenheit. Optimisten sehen eine Gelegenheit in jeder Schwierigkeit.", "Anonym", "46" ),
array( "Alles, was uns wirklich nützt, ist für wenig Geld zu haben, nur das Überflüssige kostet viel.", "Axel Munthe", "39" ),
array( "Du bist sofort die Hälfte deiner Probleme los, wenn du den Leuten nicht länger erlaubst, dass SIE dir sagen, was DU willst.", "Vernon Law", "35" ),
array( "Veränderungen machen uns vor allen Dingen deshalb Angst, weil sie uns dazu zwingen, uns aus der Hängematte der Gewohnheit heraus zu begeben", "Helga Schäferling", "23" ),
array( "Man kann nicht über seinen Schatten springen, aber man muss auch nicht immer in seinem Schatten leben", "Adolph Lowe", "5" ),
array( "Wer nichts erwartet, wird selten enttäuscht", "Ewald Balser", "7" ),
array( "Was wir am nötigsten brauchen, ist ein Mensch,der uns zwingt, das zu tun, was wir können", "Ralph Waldo Emerson", "3" ),
array( "Dort, wo die Vorstellungskraft fehlt, kann es keine Leidenschaft und als Konsequenz keine Liebe geben", "William Godwin", "1" ),
array( "Manchmal schweben Gelegenheiten direkt an deiner Nase vorbei. Arbeite hart, sei fleißig, halte dich bereit. Wenn du eine Chance bekommst dann ergreife sie", "Julie Andrews", "9" ),
array( "Jeder Mensch will glücklich werden", "das ist falsch. Jeder Mensch soll glücklich machen", "20" ),
array( "Falls Du glaubst, dass Du zu klein bist, um etwas zu bewirken, dann versuche mal zu schlafen, wenn ein Moskito im Zimmer ist", "Dalei Lama", "55" )
	  ); ?>